### PR TITLE
Ui: Basic Ui and more features

### PR DESCRIPTION
**Pull request by yewshengkai**
+ Updated basic UI (skeleton)
+ Left listview will be used as tag control (to be implmented)
+ Menubar more features (about us-working, save, etc - to be implemented as well)

### CODE REVIEW

**Comment by yewshengkai** [comment]
I think must force merge liow. I added EOF like many times (check the code). Still same error. Ltr please approve thanks.

**Comment by eugenepeh** [comment]
@yewshengkai Hi, can you try running this command `gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor` in cmd at your repo directory and show the output?

**Comment by damithc** [comment]
This PR has 70 files changed. Is that intended?

**Comment by eugenepeh** [comment]
@yewshengkai oh yes, seems like your .gitignore isn't working... here's a useful git command to fix gitignore *Note: Save your work on another branch first before trying this out*

>git rm -rf --cached .
git add .

**Comment by yewshengkai** [comment]
Hi prof and all, 

@eugenepeh running "gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidocto" on my local repo, clean and build success.

@damithc - Yes. I wanted to test opening AboutUs.html. Hence, after converting .adoc to .html (through "gradlew asciidoctor"), I duplicate all neccessary files and folder from "build" to src/main/resources/

**Comment by yewshengkai** [comment]
`Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

S:\OneDrive\04. NUS\04. SEM3 (YR3)\CS2103 Software Engineering\Workplace\main>gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls a
sciidoctor
:clean                                                                           
:compileJava                                                             
:copyStylesheets                 
:asciidoctor                                                         
io/console not supported; tty will not be manipulated
                                                      :deployOfflineDocs
:processResources                  
:classes                 
:checkstyleMain                                                        
Download https://jcenter.bintray.com/com/puppycrawl/tools/checkstyle/8.1/checkstyle-8.1.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/9/oss-parent-9.pom             
Download https://jcenter.bintray.com/antlr/antlr/2.7.7/antlr-2.7.7.pom                        
Download https://jcenter.bintray.com/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.pom
Download https://jcenter.bintray.com/org/antlr/antlr4-master/4.7/antlr4-master-4.7.pom        
Download https://jcenter.bintray.com/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/41/commons-parent-41.pom 
Download https://jcenter.bintray.com/org/apache/apache/18/apache-18.pom                         
Download https://jcenter.bintray.com/commons-cli/commons-cli/1.4/commons-cli-1.4.pom            
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/42/commons-parent-42.pom 
Download https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.pom                 
Download https://jcenter.bintray.com/com/google/guava/guava-parent/22.0/guava-parent-22.0.pom 
Download https://jcenter.bintray.com/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/39/commons-parent-39.pom 
Download https://jcenter.bintray.com/org/apache/apache/16/apache-16.pom                         
Download https://jcenter.bintray.com/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom     
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.pom
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_parent/2.0.18/error_prone_parent-2.0.18.pom
Download https://jcenter.bintray.com/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.pom
Download https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.pom
Download https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14.pom
Download https://jcenter.bintray.com/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom      
Download https://jcenter.bintray.com/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom       
Download https://jcenter.bintray.com/com/puppycrawl/tools/checkstyle/8.1/checkstyle-8.1.jar   
Download https://jcenter.bintray.com/antlr/antlr/2.7.7/antlr-2.7.7.jar
Download https://jcenter.bintray.com/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.jar
Download https://jcenter.bintray.com/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
Download https://jcenter.bintray.com/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
Download https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.jar
Download https://jcenter.bintray.com/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
Download https://jcenter.bintray.com/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
Download https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar
Download https://jcenter.bintray.com/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
Download https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
:compileTestJava                                                                  
:processTestResources                 
:testClasses                 
:checkstyleTest                 
:headless                 
Setting headless mode properties.
:allTests                                                         
Exception in thread "JavaFX Application Thread" :coverage
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.7.1.201405082137/org.jacoco.ant-0.7.1.201405082137.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.core/0.7.1.201405082137/org.jacoco.core-0.7.1.201405082137.pom
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.1.201405082137/org.jacoco.report-0.7.1.201405082137.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.pom
Download https://jcenter.bintray.com/org/ow2/asm/asm-parent/5.0.1/asm-parent-5.0.1.pom 
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.ant/0.7.1.201405082137/org.jacoco.ant-0.7.1.201405082137.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.core/0.7.1.201405082137/org.jacoco.core-0.7.1.201405082137.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.1.201405082137/org.jacoco.report-0.7.1.201405082137.jar
Download https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
:coveralls SKIPPED                                   
               
BUILD SUCCESSFUL
               
Total time: 3 mins 27.257 secs
`

**Comment by eugenepeh** [comment]
@yewshengkai you don't really have to copy the build files to your source to test it online. 

You should be able to verify that it is correct by preview it locally. 

If you want to see it online, you should be able to see it through your team's github pages (after merging into master branch) if you guys have set it up the auto deploy gh-pages using the instructions [here](https://github.com/nus-cs2103-AY1718S1/addressbook-level4/blob/master/docs/UsingTravis.adoc#enabling-auto-publishing-of-documentation).

**Comment by yewshengkai** [comment]
@eugenepeh Noted thanks! :+1: 

Yep. Local preview works fine.

**Comment by eugenepeh** [comment]
@yewshengkai yup, just remove those files to solve this error, also here's what the other developers advised in the forum

>The simplest solution is to not commit the files inside the src/main/resources/docs/ directory.What's happening is that committing the files in that directory makes them tracked by Git, which thus subjects them to the repository-wide checks. The Travis CI build runs ./gradlew assemble which overwrites the files in that directory (without the newline at EOF), and thus these files thus subsequently cause "no newline at EOF" errors.

**Comment by yewshengkai** [comment]
PR closed for further update.

**Pull request closed without merging**
